### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by eimonpakzad** [TristonStuart/ShellShockersHack#2]
it aims at your teammate

**Comment by eimonpakzad** [comment]
![Screenshot 2020-05-02 at 12 31 29 AM](https://user-images.githubusercontent.com/35317687/80855125-52827900-8c0c-11ea-98f8-768dd1963e78.png)

**Comment by TristonStuart** [comment]
Aiming at teammates has not been programmed in. I'll look into making it a feature. ESP was fixed with release V4.2.1.
